url: 'localhost:3000'
darkMode: 'on'
# Home Configuration
home:
  title: 'My Blog'
  description: 'This is a rick blog'
  gridOfPosts:
    mobile: '2'
    tablet: '2'
    desktop: '2'
  postsPerPage: '4'
  postsOrder: 'title'
  postsSort: 'ASC'

# Archive Configuration
archive:
  title: 'Blog'
  description: 'I will Share my experince and more thing...'
  gridOfPosts:
    mobile: '2'
    tablet: '3'
    desktop: '4'
  postsOrder: 'title'
  postsSort: 'ASC'
  postsPerPage: '20'
  acitveArrowPaginationAfter: 20

# Navbar Menu
menu:
  - name: 'Blog'
    link: '/blog'
  - name: 'About'
    link: '/about'

# Footer
footerText: ' Rick. All Rights Reserved.'

# Social
social:
  - name: 'twitter'
    link: '#twitter'
  - name: 'facebook'
    link: '#facebook'
  - name: 'linkedin'
    link: '#linkdin'
